# サイト設定
title: Vibecoding スタートガイド
description: プログラミング初心者のためのVibecoding入門マニュアル
lang: ja
url: https://moshimoshipandasan.github.io
baseurl: /vibecoding-manual

# テーマ設定 - Just the Docs
theme: just-the-docs
color_scheme: light

# Just the Docs 設定
logo: "/assets/images/logo.png"  # オプション：ロゴ画像
favicon_ico: "/assets/images/favicon.ico"  # オプション：ファビコン

# 検索機能
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-\./]+/
  rel_url: true
  button: false

# 外部リンク
aux_links:
  "GitHub":
    - "https://github.com/moshimoshipandasan/vibecoding-manual"

# フッターコンテンツ
footer_content: "Copyright &copy; 2024 Vibecoding Documentation Team. Distributed by an <a href=\"https://github.com/moshimoshipandasan/vibecoding-manual/blob/main/LICENSE\">MIT license.</a>"

# バックリンク
back_to_top: true
back_to_top_text: "ページトップへ"

# カラースキーム（light, dark, nilから選択）
color_scheme: light

# カスタムCSS
css: custom

# Google Analytics（オプション）
# ga_tracking: UA-XXXXXXXXX-X

# プラグイン
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown設定
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# SEO設定
author: Vibecoding Documentation Team
twitter:
  card: summary

# 出力設定
permalink: pretty
timezone: Asia/Tokyo

# ビルド除外設定
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .github/